language: csharp
mono: none
dotnet: 2.1.300
script:
  - dotnet restore
  - dotnet build ./ThreeFourteen.AlphaVantage.sln
  - dotnet test ./test/ThreeFourteen.AlphaVantage.Test
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - cd /src/ThreeFourteen.AlphaVantage && dotnet pack -c Release /p:Version=$MY_VERSION && cd bin/Release && dotnet nuget push ThreeFourteen.AlphaVantage.$MY_VERSION.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
