language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./ThreeFourteen.AlphaVantage.sln
  - dotnet test ./test/ThreeFourteen.AlphaVantage.Test
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - dotnet pack ./src/ThreeFourteen.AlphaVantage -c Release /p:Version=$MY_VERSION
    - dotnet nuget push ./src/ThreeFourteen.AlphaVantage/bin/Release/ThreeFourteen.AlphaVantage.$MY_VERSION.nupkg -k $NUGET_API_KEY
